### ISSUE TITLE
Request: Convert play-webdrive to use Play 2.0

### ISSUE THREAD

**Issue by umaar** [rkaippully/play-webdrive#10]
Any possibility of converting webdrive to work with [Play 2.0](https://github.com/playframework/Play20)?

Small guide here: http://www.objectify.be/wordpress/?p=363

**Comment by rkaippully** [comment]
Unfortunately no. I do not use Play 2.0 in my projects and do not have time to work on it at this point. Feel free to fork and implement it if you can.
